// Data model — ported from exercise-duel.html (the source-of-truth prototype).
// ponytail: kept the prototype's exact shapes (log as a date-keyed dict, `goal`,
// `auto`) rather than the design doc's renamed fields — same data, and it lets the
// logic port stay verbatim. Rename later only if a consumer needs the other names.

export type PersonId = "person1" | "person2";

export interface Profile {
  name: string;
  goal: number; // 1..7 days/week
}

export interface Favor {
  id: string;
  ower: PersonId; // who owes it
  owed: PersonId; // who receives it
  text: string;
  status: "pending" | "done";
  createdAt: number; // epoch ms
  auto: boolean; // true if auto-generated by a missed weekly goal
}

// log[dateStr] = { person1?: true, person2?: true }
export type DayLog = Partial<Record<PersonId, boolean>>;

// A compressed workout-proof photo, stored inline in the synced state blob.
export interface Photo {
  uri: string; // small JPEG as a data: URL (base64) — see photo.ts
  at: number; // epoch ms captured
}

// photos[dateStr] = { person1?: Photo, person2?: Photo }
export type DayPhotos = Partial<Record<PersonId, Photo>>;

export interface AppState {
  profiles: Record<PersonId, Profile>;
  log: Record<string, DayLog>;
  favors: Favor[];
  lastWeekProcessed: string; // "YYYY-MM-DD" Monday of last-checked week
  // Optional so states saved before this feature still load. Kept small +
  // pruned (see photo.ts) so the whole blob stays under DynamoDB's item limit.
  photos?: Record<string, DayPhotos>;
}
