// Data model — ported from exercise-duel.html (the source-of-truth prototype).
// ponytail: kept the prototype's exact shapes (log as a date-keyed dict, `goal`,
// `auto`) rather than the design doc's renamed fields — same data, and it lets the
// logic port stay verbatim. Rename later only if a consumer needs the other names.

export type PersonId = "person1" | "person2";

export interface Profile {
  name: string;
  goal: number; // 1..7 days/week
}

export interface Favor {
  id: string;
  ower: PersonId; // who owes it
  owed: PersonId; // who receives it
  text: string;
  status: "pending" | "done";
  createdAt: number; // epoch ms
  auto: boolean; // true if auto-generated by a missed weekly goal
}

// log[dateStr] = { person1?: true, person2?: true }
export type DayLog = Partial<Record<PersonId, boolean>>;

export interface AppState {
  profiles: Record<PersonId, Profile>;
  log: Record<string, DayLog>;
  favors: Favor[];
  lastWeekProcessed: string; // "YYYY-MM-DD" Monday of last-checked week
}
